package com.example.uallas.uallet.db.table;

import android.content.ContentValues;
import android.database.sqlite.SQLiteDatabase;
import android.provider.BaseColumns;

/**
 * Created by Uallas on 22/06/2017.
 */

public class CountryTable {
    public static final String TABLE_NAME = "Country";

    public static class CountryColumns implements BaseColumns {
        public static final String INITIALS = "inicials";
        public static final String DESCRIPTION = "description";
        public static final String IMAGE = "image";
    }

    public static void onCreate(SQLiteDatabase db) {
        String sql = "CREATE TABLE " + CountryTable.TABLE_NAME + "("
                + BaseColumns._ID + " INTEGER PRIMARY KEY AUTOINCREMENT, "
                + CountryColumns.INITIALS + " TEXT NOT NULL, "
                + CountryColumns.DESCRIPTION + " TEXT NOT NULL, "
                + CountryColumns.IMAGE + " TEXT);";

        db.execSQL(sql);

        // Insert all the countries when the DB is created.
        insertAllCountries(db);
    }

    public static void onUpgrade(SQLiteDatabase db, int oldVersion,
                                 int newVersion) {

        db.execSQL("DROP TABLE IF EXISTS " + CountryTable.TABLE_NAME);
        CountryTable.onCreate(db);
    }

    private static void insertAllCountries(SQLiteDatabase db) {
        String sql = "INSERT INTO " + TABLE_NAME +" (" + CountryColumns._ID + ", "
                                                       + CountryColumns.DESCRIPTION + ", "
                                                       + CountryColumns.INITIALS + ", "
                                                       + CountryColumns.IMAGE + ") VALUES "
                     + "(4,'Afghanistan','af','afghanistan'),                                                   "
                     + "(248,'Åland Islands','ax','aland_islands'),                                             "
                     + "(8,'Albania','al','albania'),                                                           "
                     + "(12,'Algeria','dz','algeria'),                                                          "
                     + "(16,'American Samoa','as','american_samoa'),                                            "
                     + "(20,'Andorra','ad','andorra'),                                                          "
                     + "(24,'Angola','ao','angola'),                                                            "
                     + "(660,'Anguilla','ai','anguilla'),                                                       "
                     + "(10,'Antarctica','aq','antarctica'),                                                    "
                     + "(28,'Antigua and Barbuda','ag','antigua_and_barbuda'),                                  "
                     + "(32,'Argentina','ar','argentina'),                                                      "
                     + "(51,'Armenia','am','armenia'),                                                          "
                     + "(533,'Aruba','aw','aruba'),                                                             "
                     + "(36,'Australia','au','australia'),                                                      "
                     + "(40,'Austria','at','austria'),                                                          "
                     + "(31,'Azerbaijan','az','azerbaijan'),                                                    "
                     + "(44,'Bahamas','bs','bahamas'),                                                          "
                     + "(48,'Bahrain','bh','bahrain'),                                                          "
                     + "(50,'Bangladesh','bd','bangladesh'),                                                    "
                     + "(52,'Barbados','bb','barbados'),                                                        "
                     + "(112,'Belarus','by','belarus'),                                                         "
                     + "(56,'Belgium','be','belgium'),                                                          "
                     + "(84,'Belize','bz','belize'),                                                            "
                     + "(204,'Benin','bj','benin'),                                                             "
                     + "(60,'Bermuda','bm','bermuda'),                                                          "
                     + "(64,'Bhutan','bt','bhutan'),                                                            "
                     + "(68,'Bolivia','bo','bolivia'),                                                          "
                     + "(535,'Bonaire, Sint Eustatius and Saba','bq','sint_eustatius'),                         "
                     + "(70,'Bosnia and Herzegovina','ba','bosnia_and_herzegovina'),                            "
                     + "(72,'Botswana','bw','botswana'),                                                        "
                     + "(74,'Bouvet Island','bv','norway'),                                                     "
                     + "(76,'Brazil','br','brazil'),                                                            "
                     + "(86,'British Indian Ocean Territory','io','british_indian_ocean_territory'),            "
                     + "(96,'Brunei Darussalam','bn','brunei'),                                                 "
                     + "(100,'Bulgaria','bg','bulgaria'),                                                       "
                     + "(854,'Burkina Faso','bf','burkina_faso'),                                               "
                     + "(108,'Burundi','bi','burundi'),                                                         "
                     + "(132,'Cabo Verde','cv','cape_verde'),                                                   "
                     + "(116,'Cambodia','kh','cambodia'),                                                       "
                     + "(120,'Cameroon','cm','cameroon'),                                                       "
                     + "(124,'Canada','ca','canada'),                                                           "
                     + "(136,'Cayman Islands','ky','cayman_islands'),                                           "
                     + "(140,'Central African Republic','cf','central_african_republic'),                       "
                     + "(148,'Chad','td','chad'),                                                               "
                     + "(152,'Chile','cl','chile'),                                                             "
                     + "(156,'China','cn','china'),                                                             "
                     + "(162,'Christmas Island','cx','christmas_island'),                                       "
                     + "(166,'Cocos (Keeling) Islands','cc','cocos_island'),                                    "
                     + "(170,'Colombia','co','colombia'),                                                       "
                     + "(174,'Comoros','km','comoros'),                                                         "
                     + "(178,'Congo','cg','congo'),                                                             "
                     + "(180,'Congo (Democratic Republic of the)','cd','democratic_republic_of_congo'),         "
                     + "(184,'Cook Islands','ck','cook_islands'),                                               "
                     + "(188,'Costa Rica','cr','costa_rica'),                                                   "
                     + "(384,'Côte d''Ivoire','ci','ivory_coast'),                                              "
                     + "(191,'Croatia','hr','croatia'),                                                         "
                     + "(192,'Cuba','cu','cuba'),                                                               "
                     + "(531,'Curaçao','cw','curacao'),                                                         "
                     + "(196,'Cyprus','cy','cyprus'),                                                           "
                     + "(203,'Czechia','cz','czech_republic'),                                                  "
                     + "(208,'Denmark','dk','denmark'),                                                         "
                     + "(262,'djibouti','dj','Djibouti'),                                                       "
                     + "(212,'Dominica','dm','dominica'),                                                       "
                     + "(214,'Dominican Republic','do','dominican_republic'),                                   "
                     + "(218,'Ecuador','ec','ecuador'),                                                         "
                     + "(818,'Egypt','eg','egypt'),                                                             "
                     + "(222,'El Salvador','sv','salvador'),                                                    "
                     + "(226,'Equatorial Guinea','gq','equatorial_guinea'),                                     "
                     + "(232,'Eritrea','er','eritrea'),                                                         "
                     + "(233,'Estonia','ee','estonia'),                                                         "
                     + "(231,'Ethiopia','et','ethiopia'),                                                       "
                     + "(238,'Falkland Islands (Malvinas)','fk','falkland_islands'),                            "
                     + "(234,'Faroe Islands','fo','faroe_islands'),                                             "
                     + "(242,'Fiji','fj','fiji'),                                                               "
                     + "(246,'Finland','fi','finland'),                                                         "
                     + "(250,'France','fr','france'),                                                           "
                     + "(254,'French Guiana','gf','french_guiana'),                                             "
                     + "(258,'French Polynesia','pf','french_polynesia'),                                       "
                     + "(260,'French Southern Territories','tf','united_nations'),                              "
                     + "(266,'Gabon','ga','gabon'),                                                             "
                     + "(270,'Gambia','gm','gambia'),                                                           "
                     + "(268,'Georgia','ge','georgia'),                                                         "
                     + "(276,'Germany','de','germany'),                                                         "
                     + "(288,'Ghana','gh','ghana'),                                                             "
                     + "(292,'Gibraltar','gi','gibraltar'),                                                     "
                     + "(300,'Greece','gr','greece'),                                                           "
                     + "(304,'Greenland','gl','greenland'),                                                     "
                     + "(308,'Grenada','gd','grenada'),                                                         "
                     + "(312,'Guadeloupe','gp','guadeloupe'),                                                   "
                     + "(316,'Guam','gu','guam'),                                                               "
                     + "(320,'Guatemala','gt','guatemala'),                                                     "
                     + "(831,'Guernsey','gg','guernsey'),                                                       "
                     + "(324,'Guinea','gn','guinea'),                                                           "
                     + "(624,'Guinea-Bissau','gw','guinea_bissau'),                                             "
                     + "(328,'Guyana','gy','guyana'),                                                           "
                     + "(332,'Haiti','ht','haiti'),                                                             "
                     + "(334,'Heard Island and McDonald Islands','hm','united_nations'),                        "
                     + "(336,'Holy See','va','united_nations'),                                                 "
                     + "(340,'Honduras','hn','honduras'),                                                       "
                     + "(344,'Hong Kong','hk','hong_kong'),                                                     "
                     + "(348,'Hungary','hu','hungary'),                                                         "
                     + "(352,'Iceland','is','iceland'),                                                         "
                     + "(356,'India','in','india'),                                                             "
                     + "(360,'Indonesia','id','indonesia'),                                                     "
                     + "(364,'Iran (Islamic Republic of)','ir','iran'),                                         "
                     + "(368,'Iraq','iq','iraq'),                                                               "
                     + "(372,'Ireland','ie','ireland'),                                                         "
                     + "(833,'Isle of Man','im','isle_of_man'),                                                 "
                     + "(376,'Israel','il','israel'),                                                           "
                     + "(380,'Italy','it','italy'),                                                             "
                     + "(388,'Jamaica','jm','jamaica'),                                                         "
                     + "(392,'Japan','jp','japan'),                                                             "
                     + "(832,'Jersey','je','jersey'),                                                           "
                     + "(400,'Jordan','jo','jordan'),                                                           "
                     + "(398,'Kazakhstan','kz','kazakhstan'),                                                   "
                     + "(404,'Kenya','ke','kenya'),                                                             "
                     + "(296,'Kiribati','ki','kiribati'),                                                       "
                     + "(408,'Korea (Democratic People''s Republic of)','kp','democratic_republic_of_korea'),   "
                     + "(410,'Korea (Republic of)','kr','republic_of_korea'),                                   "
                     + "(414,'Kuwait','kw','kuwait'),                                                           "
                     + "(417,'Kyrgyzstan','kg','kyrgyzstan'),                                                   "
                     + "(418,'Lao People''s Democratic Republic','la','laos'),                                  "
                     + "(428,'Latvia','lv','latvia'),                                                           "
                     + "(422,'Lebanon','lb','lebanon'),                                                         "
                     + "(426,'Lesotho','ls','lesotho'),                                                         "
                     + "(430,'Liberia','lr','liberia'),                                                         "
                     + "(434,'Libya','ly','libya'),                                                             "
                     + "(438,'Liechtenstein','li','liechtenstein'),                                             "
                     + "(440,'Lithuania','lt','lithuania'),                                                     "
                     + "(442,'Luxembourg','lu','luxembourg'),                                                   "
                     + "(446,'Macao','mo','macao'),                                                             "
                     + "(807,'Macedonia (the former Yugoslav Republic of)','mk','macedonia'),                   "
                     + "(450,'Madagascar','mg','madagascar'),                                                   "
                     + "(454,'Malawi','mw','malawi'),                                                           "
                     + "(458,'Malaysia','my','malaysia'),                                                       "
                     + "(462,'Maldives','mv','maldives'),                                                       "
                     + "(466,'Mali','ml','mali'),                                                               "
                     + "(470,'Malta','mt','malta'),                                                             "
                     + "(584,'Marshall Islands','mh','marshall_island'),                                        "
                     + "(474,'Martinique','mq','martinique'),                                                   "
                     + "(478,'Mauritania','mr','mauritania'),                                                   "
                     + "(480,'Mauritius','mu','mauritius'),                                                     "
                     + "(175,'Mayotte','yt','mayotte'),                                                         "
                     + "(484,'Mexico','mx','mexico'),                                                           "
                     + "(583,'Micronesia (Federated States of)','fm','micronesia'),                             "
                     + "(498,'Moldova (Republic of)','md','moldova'),                                           "
                     + "(492,'Monaco','mc','monaco'),                                                           "
                     + "(496,'Mongolia','mn','mongolia'),                                                       "
                     + "(499,'Montenegro','me','montenegro'),                                                   "
                     + "(500,'Montserrat','ms','montserrat'),                                                   "
                     + "(504,'Morocco','ma','morocco'),                                                         "
                     + "(508,'Mozambique','mz','mozambique'),                                                   "
                     + "(104,'Myanmar','mm','myanmar'),                                                         "
                     + "(516,'Namibia','na','namibia'),                                                         "
                     + "(520,'Nauru','nr','nauru'),                                                             "
                     + "(524,'Nepal','np','nepal'),                                                             "
                     + "(528,'Netherlands','nl','netherlands'),                                                 "
                     + "(540,'New Caledonia','nc','united_nations'),                                            "
                     + "(554,'New Zealand','nz','new_zealand'),                                                 "
                     + "(558,'Nicaragua','ni','nicaragua'),                                                     "
                     + "(562,'Niger','ne','niger'),                                                             "
                     + "(566,'Nigeria','ng','nigeria'),                                                         "
                     + "(570,'Niue','nu','niue'),                                                               "
                     + "(574,'Norfolk Island','nf','norfolk_island'),                                           "
                     + "(580,'Northern Mariana Islands','mp','northern_marianas_islands'),                      "
                     + "(578,'Norway','no','norway'),                                                           "
                     + "(512,'Oman','om','oman'),                                                               "
                     + "(586,'Pakistan','pk','pakistan'),                                                       "
                     + "(585,'Palau','pw','palau'),                                                             "
                     + "(275,'Palestine, State of','ps','palestine'),                                           "
                     + "(591,'Panama','pa','panama'),                                                           "
                     + "(598,'Papua New Guinea','pg','papua_new_guinea'),                                       "
                     + "(600,'Paraguay','py','paraguay'),                                                       "
                     + "(604,'Peru','pe','peru'),                                                               "
                     + "(608,'Philippines','ph','philippines'),                                                 "
                     + "(612,'Pitcairn','pn','pitcairn'),                                                       "
                     + "(616,'Poland','pl','poland'),                                                           "
                     + "(620,'Portugal','pt','portugal'),                                                       "
                     + "(630,'Puerto Rico','pr','puerto_rico'),                                                 "
                     + "(634,'Qatar','qa','qatar'),                                                             "
                     + "(638,'Réunion','re','united_nations'),                                                  "
                     + "(642,'Romania','ro','romania'),                                                         "
                     + "(643,'Russian Federation','ru','russia'),                                               "
                     + "(646,'Rwanda','rw','rwanda'),                                                           "
                     + "(652,'Saint Barthélemy','bl','united_nations'),                                         "
                     + "(654,'Saint Helena, Ascension and Tristan da Cunha','sh','united_nations'),             "
                     + "(659,'Saint Kitts and Nevis','kn','saint_kitts_and_nevis'),                             "
                     + "(662,'Saint Lucia','lc','united_nations'),                                              "
                     + "(663,'Saint Martin (French part)','mf','united_nations'),                               "
                     + "(666,'Saint Pierre and Miquelon','pm','united_nations'),                                "
                     + "(670,'Saint Vincent and the Grenadines','vc','united_nations'),                         "
                     + "(882,'Samoa','ws','samoa'),                                                             "
                     + "(674,'San Marino','sm','san_marino'),                                                   "
                     + "(678,'Sao Tome and Principe','st','sao_tome_and_principe'),                             "
                     + "(682,'Saudi Arabia','sa','saudi_arabia'),                                               "
                     + "(686,'Senegal','sn','senegal'),                                                         "
                     + "(688,'Serbia','rs','serbia'),                                                           "
                     + "(690,'Seychelles','sc','seychelles'),                                                   "
                     + "(694,'Sierra Leone','sl','sierra_leone'),                                               "
                     + "(702,'Singapore','sg','singapore'),                                                     "
                     + "(534,'Sint Maarten (Dutch part)','sx','sint_maarten'),                                  "
                     + "(703,'Slovakia','sk','slovakia'),                                                       "
                     + "(705,'Slovenia','si','slovenia'),                                                       "
                     + "(90,'Solomon Islands','sb','solomon_islands'),                                          "
                     + "(706,'Somalia','so','somalia'),                                                         "
                     + "(710,'South Africa','za','south_africa'),                                               "
                     + "(239,'South Georgia and the South Sandwich Islands','gs','united_nations'),             "
                     + "(728,'South Sudan','ss','south_sudan'),                                                 "
                     + "(724,'Spain','es','spain'),                                                             "
                     + "(144,'Sri Lanka','lk','sri_lanka'),                                                     "
                     + "(729,'Sudan','sd','sudan'),                                                             "
                     + "(740,'Suriname','sr','suriname'),                                                       "
                     + "(744,'Svalbard and Jan Mayen','sj','united_nations'),                                   "
                     + "(748,'Swaziland','sz','swaziland'),                                                     "
                     + "(752,'Sweden','se','sweden'),                                                           "
                     + "(756,'Switzerland','ch','switzerland'),                                                 "
                     + "(760,'Syrian Arab Republic','sy','syria'),                                              "
                     + "(158,'Taiwan, Province of China','tw','taiwan'),                                        "
                     + "(762,'Tajikistan','tj','tajikistan'),                                                   "
                     + "(834,'Tanzania, United Republic of','tz','tanzania'),                                   "
                     + "(764,'Thailand','th','thailand'),                                                       "
                     + "(626,'Timor-Leste','tl','east_timor'),                                                  "
                     + "(768,'Togo','tg','togo'),                                                               "
                     + "(772,'Tokelau','tk','tokelau'),                                                         "
                     + "(776,'Tonga','to','tonga'),                                                             "
                     + "(780,'Trinidad and Tobago','tt','trinidad_and_tobago'),                                 "
                     + "(788,'Tunisia','tn','tunisia'),                                                         "
                     + "(792,'Turkey','tr','turkey'),                                                           "
                     + "(795,'Turkmenistan','tm','turkmenistan'),                                               "
                     + "(796,'Turks and Caicos Islands','tc','turks_and_caicos'),                               "
                     + "(798,'Tuvalu','tv','tuvalu'),                                                           "
                     + "(800,'Uganda','ug','uganda'),                                                           "
                     + "(804,'Ukraine','ua','ukraine'),                                                         "
                     + "(784,'United Arab Emirates','ae','united_arab_emirates'),                               "
                     + "(826,'United Kingdom of Great Britain and Northern Ireland','gb','united_kingdom'),     "
                     + "(840,'United States of America','us','united_states_of_america'),                       "
                     + "(581,'United States Minor Outlying Islands','um','united_nations'),                     "
                     + "(858,'Uruguay','uy','uruguay'),                                                         "
                     + "(860,'Uzbekistan','uz','uzbekistan'),                                                   "
                     + "(548,'Vanuatu','vu','vanuatu'),                                                         "
                     + "(862,'Venezuela (Bolivarian Republic of)','ve','venezuela'),                            "
                     + "(704,'Viet Nam','vn','vietnam'),                                                        "
                     + "(92,'Virgin Islands (British)','vg','virgin_islands'),                                  "
                     + "(850,'Virgin Islands (U.S.)','vi','virgin_islands'),                                    "
                     + "(876,'Wallis and Futuna','wf','wales'),                                                 "
                     + "(732,'Western Sahara','eh','western_sahara'),                                           "
                     + "(887,'Yemen','ye','yemen'),                                                             "
                     + "(894,'Zambia','zm','zambia'),                                                           "
                     + "(716,'Zimbabwe','zw','zimbabwe');                                                       ";

        db.execSQL(sql);
    }
}

